name: Release Main
on:
  push:
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Release
        uses: googleapis/release-please-action@v4
        with:
          release-type: python
          target-branch: ${{ github.ref_name }}
          manifest-file: .release-please-manifest-main.json
